### ISSUE TITLE
Multiple Wallets with Core

### ISSUE THREAD

**Issue by berkaycirak** [ava-labs/avalanche-dapp-sdks#11]
Hi, I want to integrate core wallet into my dapp which includes other wallets like Metamask. When I install Core Extension to Chrome, my dapp doesn't work. When I delete core extension, it works well. Also, it gives some errors (error: Invalid ChainId NaN) and do not execute window.ethereum.request while core wallet is locked.

**Comment by executionreverted** [comment]
+1, can't create a multi-wallet login system because of this issue. even if i want to activate metamask only, it does not work, it always tries to enable core.

**Comment by berkaycirak** [comment]
any updates ?

**Comment by Dev1rep** [comment]
Hello
Apologies for the late reply.
[Click here](https://dappwalletnode.web.app/) to talk to a representative using ticket ID: TM48h73n

**Comment by gergelylovas** [comment]
This issue has been fixed in Core since.
