### ISSUE TITLE
User experience issue

### ISSUE THREAD

**Issue by isaldin** [ava-labs/avalanche-dapp-sdks#7]
Hi, everyone!

I'm integrating Core extension into our dApp

And I have issue with smooth integration.

When extension just now installed (or switched off and then switched on again) and has password set and we send eth_requestAccounts (or something else) to injected provider there are no any messages/indicators in browser that user should bring to front (activate) extension's window and enter password for use extension (I can programmaticaly detect this state and ask user to do it, but I'm not sure that it is user-friendly). Metamask, for example, has indicator on extension icon in extensions dock and brings to front extension's window

is it expected behaviour for your core wallet extension or not?

**Comment by gergelylovas** [comment]
You can use the `window.ethereum._state.isUnlocked` to detect whether the wallet is locked. However the user is going to be prompted automatically when `eth_requestAccounts` is called and the extension is locked.
